---
apiVersion: v1
kind: Pod
metadata:
  name: simple-website
  labels:
    app: simple-website
spec:
  containers:
  - name: simple-website
    image: dipugodocker/simple-website:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /
        port: 80
    ports:
      - containerPort: 80
...